services:
  - type: worker
    name: yogabot-schedule
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: ADMINS
        sync: false
